### PR TITLE
Add filter functionality

### PR DESCRIPTION
**Pull request by bezoerb**

### CODE REVIEW

**Comment by bezoerb** [comment]
hmm,... i somehow don't like the change of the api introduced by this PR. Adding a function as last parameter looks like making an async call. Any thoughts on this?

**Comment by addyosmani** [comment]
I don't have a better suggestion off the top of my head right now, but agree that it does look a little strange the way we have it setup in this PR. Do you need this for work being done elsewhere or do we have time to sit and think about this a bit?

**Comment by bezoerb** [comment]
No hurry on this. I prefer the "sit and think" alternative ;)

**Comment by luckyraul** [comment]
@bezoerb @addyosmani any updates ?

**Comment by bezoerb** [comment]
Changed the implementation to allow:

```js
var srcs = oust.raw(htmlString, '...');

 -> [
    {value: '...', $el: '...'},
    {value: '...', $el: '...'},
    ...
 ]
```

Filtering can now be achieved with the additional `$el` in the result set.

**Comment by bezoerb** [comment]
@addyosmani: I'm just cleaning up some outdated issues over at critical and i've stumbled across this one (https://github.com/addyosmani/critical/issues/113) 
What do you think about the latest changes to this PR? Wanna get this landed?

**Comment by addyosmani** [comment]
Let's land it. Thanks for the reminder, @bezoerb! 

Side: I have to greatly apologize for the lack of response on some of the issues I've been tagged in across a few repos. I can't thank you enough for your help with the clean-up!

**Pull request merged**
